---
language: ruby
rvm: 2.4
cache: bundler # see https://docs.travis-ci.com/user/caching/

services:
- docker

env:
- JEKYLL_ENV=production

jobs:
  include:
  - stage: test
    script:
    - bundle exec rake -t build
    - bundle exec rake -t test EXT=0
  - stage: deploy
    script: bundle exec rake -t build
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      target_branch: master
      fqdn: olbat.net
      local_dir: _site/
      on:
        branch: source
    after_deploy: # flush Cloudflare's cache
    - curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONEID/purge_cache" \
        -H "X-Auth-Email: ${CLOUDFLARE_USER}" \
        -H "X-Auth-Key: ${CLOUDFLARE_TOKEN}" \
        -H "Content-Type: application/json" --data '{"purge_everything":true}'
