---
language: ruby
rvm: 2.4

env:
- JEKYLL_ENV=production

jobs:
  include:
  - stage: test
    script:
    - bundle exec rake -t build
    - bundle exec rake test
    - bundle exec rake -t test
  - stage: deploy
    script: bundle exec rake -t build
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      target_branch: master
      fqdn: olbat.net
      local_dir: _site/
      on:
        branch: source
