---
language: ruby
rvm: 2.4

env:
- JEKYLL_ENV=production

script:
- bundle exec jekyll build -V

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  fqdn: olbat.net
  local_dir: _site/
  on:
    branch: source
